from app.checklists.models import ChecklistConfig
from app.checklists.definitions.helpers import groups_from_list


R_GROUPS = [
    {
        "id": 1,
        "title": "Общие данные",
        "items": [
            "Состав проекта",
            "Заполнение Штампа",
            "Титульные листы",
        ],
    },
    {
        "id": 2,
        "title": "Чек-лист Стадия Р",
        "items": [
            "ГП",
            "АР",
            "КМ, КЖ",
            "ЭС, ЭОМ",
            "ВК",
            "ОВ",
            "СС",
            "ПС",
            "ТХ",
        ],
    },
    {
        "id": 3,
        "title": "Экспертиза РД",
        "items": [
            "Замечания заказчика",
            "Ответы на замечания",
            "Заключение экспертизы",
        ],
    },
    {
        "id": 5,
        "title": "Задания смежным специалистам",
        "items": [],
    },
    {
        "id": 90,
        "title": "BIM-Модель",
        "items": [
            "BIM",
            "ГП",
            "БЛ",
            "НИС",
            "АР",
            "АИ",
            "ФР",
            "КР",
            "ОВ",
            "ВК",
            "ЭОМ",
            "СС",
            "ТХ",
        ],
    },
    {
        "id": 4,
        "title": "Не требуется",
        "items": [],
    },
]


STANDARD_R_YANDEX_FOLDER_SPECS = {
    "r_project_composition": {
        "groupId": 1,
        "itemName": "Состав проекта",
        "alias": "r_project_composition",
        "folderName": "01_Состав проекта",
        "relativePath": "01_Общие данные/01_Состав проекта",
    },
    "r_stamp_filling": {
        "groupId": 1,
        "itemName": "Заполнение Штампа",
        "alias": "r_stamp_filling",
        "folderName": "02_Заполнение штампа",
        "relativePath": "01_Общие данные/02_Заполнение штампа",
    },
    "r_title_pages": {
        "groupId": 1,
        "itemName": "Титульные листы",
        "alias": "r_title_pages",
        "folderName": "03_Титульные листы",
        "relativePath": "01_Общие данные/03_Титульные листы",
    },

    "r_gp": {
        "groupId": 2,
        "itemName": "ГП",
        "alias": "r_gp",
        "folderName": "01_ГП",
        "relativePath": "02_Стадия Р/01_ГП",
    },
    "r_ar": {
        "groupId": 2,
        "itemName": "АР",
        "alias": "r_ar",
        "folderName": "02_АР",
        "relativePath": "02_Стадия Р/02_АР",
    },
    "r_km_kj": {
        "groupId": 2,
        "itemName": "КМ, КЖ",
        "alias": "r_km_kj",
        "folderName": "03_КМ, КЖ",
        "relativePath": "02_Стадия Р/03_КМ, КЖ",
    },
    "r_es_eom": {
        "groupId": 2,
        "itemName": "ЭС, ЭОМ",
        "alias": "r_es_eom",
        "folderName": "04_ЭС, ЭОМ",
        "relativePath": "02_Стадия Р/04_ЭС, ЭОМ",
    },
    "r_vk": {
        "groupId": 2,
        "itemName": "ВК",
        "alias": "r_vk",
        "folderName": "05_ВК",
        "relativePath": "02_Стадия Р/05_ВК",
    },
    "r_ov": {
        "groupId": 2,
        "itemName": "ОВ",
        "alias": "r_ov",
        "folderName": "06_ОВ",
        "relativePath": "02_Стадия Р/06_ОВ",
    },
    "r_ss": {
        "groupId": 2,
        "itemName": "СС",
        "alias": "r_ss",
        "folderName": "07_СС",
        "relativePath": "02_Стадия Р/07_СС",
    },
    "r_ps": {
        "groupId": 2,
        "itemName": "ПС",
        "alias": "r_ps",
        "folderName": "08_ПС",
        "relativePath": "02_Стадия Р/08_ПС",
    },
    "r_tx": {
        "groupId": 2,
        "itemName": "ТХ",
        "alias": "r_tx",
        "folderName": "09_ТХ",
        "relativePath": "02_Стадия Р/09_ТХ",
    },

    "r_customer_comments": {
        "groupId": 3,
        "itemName": "Замечания заказчика",
        "alias": "r_customer_comments",
        "folderName": "Замечания заказчика",
        "relativePath": "03_Экспертиза РД/Замечания заказчика",
    },
    "r_customer_answers": {
        "groupId": 3,
        "itemName": "Ответы на замечания",
        "alias": "r_customer_answers",
        "folderName": "Ответы на замечания",
        "relativePath": "03_Экспертиза РД/Ответы на замечания",
    },
    "r_expertise_conclusion": {
        "groupId": 3,
        "itemName": "Заключение экспертизы",
        "alias": "r_expertise_conclusion",
        "folderName": "Заключение экспертизы",
        "relativePath": "03_Экспертиза РД/Заключение экспертизы",
    },

    "r_adjacent_tasks_root": {
        "groupId": 5,
        "itemName": "Задания смежным специалистам",
        "alias": "r_adjacent_tasks_root",
        "folderName": "05_Задания смежникам",
        "relativePath": "05_Задания смежникам",
        "customItemsRoot": True,
    },
    "r_bim_root": {
        "groupId": 90,
        "itemName": "BIM-Модель",
        "alias": "r_bim_root",
        "folderName": "04_BIM-Модель",
        "relativePath": "04_BIM-Модель",
    },
    "r_bim_bim": {
        "groupId": 90,
        "itemName": "BIM",
        "alias": "r_bim_bim",
        "folderName": "00_BIM",
        "relativePath": "04_BIM-Модель/00_BIM",
    },
    "r_bim_gp": {
        "groupId": 90,
        "itemName": "ГП",
        "alias": "r_bim_gp",
        "folderName": "01_ГП",
        "relativePath": "04_BIM-Модель/01_ГП",
    },
    "r_bim_bl": {
        "groupId": 90,
        "itemName": "БЛ",
        "alias": "r_bim_bl",
        "folderName": "02_БЛ",
        "relativePath": "04_BIM-Модель/02_БЛ",
    },
    "r_bim_nis": {
        "groupId": 90,
        "itemName": "НИС",
        "alias": "r_bim_nis",
        "folderName": "03_НИС",
        "relativePath": "04_BIM-Модель/03_НИС",
    },
    "r_bim_ar": {
        "groupId": 90,
        "itemName": "АР",
        "alias": "r_bim_ar",
        "folderName": "04_АР",
        "relativePath": "04_BIM-Модель/04_АР",
    },
    "r_bim_ai": {
        "groupId": 90,
        "itemName": "АИ",
        "alias": "r_bim_ai",
        "folderName": "05_АИ",
        "relativePath": "04_BIM-Модель/05_АИ",
    },
    "r_bim_fr": {
        "groupId": 90,
        "itemName": "ФР",
        "alias": "r_bim_fr",
        "folderName": "06_ФР",
        "relativePath": "04_BIM-Модель/06_ФР",
    },
    "r_bim_kr": {
        "groupId": 90,
        "itemName": "КР",
        "alias": "r_bim_kr",
        "folderName": "07_КР",
        "relativePath": "04_BIM-Модель/07_КР",
    },
    "r_bim_ov": {
        "groupId": 90,
        "itemName": "ОВ",
        "alias": "r_bim_ov",
        "folderName": "08_ОВ",
        "relativePath": "04_BIM-Модель/08_ОВ",
    },
    "r_bim_vk": {
        "groupId": 90,
        "itemName": "ВК",
        "alias": "r_bim_vk",
        "folderName": "09_ВК",
        "relativePath": "04_BIM-Модель/09_ВК",
    },
    "r_bim_eom": {
        "groupId": 90,
        "itemName": "ЭОМ",
        "alias": "r_bim_eom",
        "folderName": "10_ЭОМ",
        "relativePath": "04_BIM-Модель/10_ЭОМ",
    },
    "r_bim_ss": {
        "groupId": 90,
        "itemName": "СС",
        "alias": "r_bim_ss",
        "folderName": "11_СС",
        "relativePath": "04_BIM-Модель/11_СС",
    },
    "r_bim_tx": {
        "groupId": 90,
        "itemName": "ТХ",
        "alias": "r_bim_tx",
        "folderName": "12_ТХ",
        "relativePath": "04_BIM-Модель/12_ТХ",
    },
}


CHECKLIST_CONFIG = ChecklistConfig(
    key="r",
    title="Чек-лист Стадия Р",
    groups=groups_from_list(R_GROUPS),
    not_required_group_id=4,
    default_group_id=2,
    allow_custom_item_group_ids=(1, 2, 3, 5),
    order=50,
    yandex_root_relative_path="02_Выдача документации/04_Стадия Р",
    yandex_root_alias="r_stage_root",
    yandex_root_folder_name="04_Стадия Р",
    reset_status_on_last_document_removed=True,
    standard_yandex_folder_specs=STANDARD_R_YANDEX_FOLDER_SPECS,
    stage_yandex_folder_alias="r_stage_root",
    layout_mode="stage_with_bim",
    bim_group_id=90,
    bim_placement="below_first_group",
)
